[theme]
primaryColor = "#DA7756"
backgroundColor = "#181816"
secondaryBackgroundColor = "#1E1E1C"
textColor = "#ECEAE4"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
